# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  lib:
    taskfile: ../../../.tasks.lib.yml
    internal: true

tasks:
  run-tests:
    vars:
      file: "2d_compressible_ALA.py"
    sources:
      - "{{.file}}"
    generates:
      - "params.log"
      - "*.pvd"
      - "*.vtu"
      - "*.pvtu"
      - "*.h5"
      - "output/"
      - "reference_state/"
    cmds:
      - task: lib:run-python
        vars:
          file: "{{.file}}"
          cpus: 4

  convert-notebooks:
    cmds:
      - task: lib:convert-notebook
        vars:
          file_base: "2d_compressible_ALA"

  add-files-to-archive:
    cmds:
      - task: lib:add-files-to-archive
        vars:
          archive: "{{.archive}}"
          files: ["2d_compressible_ALA.ipynb"]
