# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  run-python:
    vars:
      cpus: "{{default 1 .cpus}}"
    cmds:
      - echo "running {{.file}} -np {{.cpus}}"

  convert-notebook:
    vars:
      input: "{{.file_base}}.py"
      output: "{{.file_base}}.ipynb"
    sources:
      - "{{.input}}"
    generates:
      - "{{.output}}"
    cmds:
      - echo "converting {{.input}} to {{.output}}"

  add-files-to-archive:
    cmds:
      - 'echo tar --append --file {{.archive}} {{.files | join " "}}'
