# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  run-python:
    run: always
    requires:
      vars:
        - file
    sources:
      - "{{.file}}"
    vars:
      tsp_string: "{{if .BATCH_MODE}}tsp -f {{if gt (.cpus | default 1) 1}}-N {{.cpus}} {{end}}{{end}}"
      mpi_string: "{{if gt (.cpus | default 1) 1}}mpiexec -np {{.cpus}} {{end}}"
    cmds:
      - "{{.tsp_string}}{{.mpi_string}}python3 {{.file}} {{.args}}"

  convert-notebook:
    vars:
      input: "{{.file_base}}.py"
      output: "{{.file_base}}.ipynb"
    sources:
      - "{{.input}}"
    generates:
      - "{{.output}}"
    cmds:
      - echo "converting {{.input}} to {{.output}}"

  add-files-to-archive:
    cmds:
      - 'echo tar --append --file {{.archive}} {{.files | join " "}}'
