# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  run-python:
    vars:
      cpus: "{{default 1 .cpus}}"
    cmds:
      - echo "running {{.file}} -np {{.cpus}}"
