[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gadopt"
version = "2.0.0"
authors = [
  { name = "G-ADOPT Contributors" }
]
description = "A computational platform for inverse geodynamics"
readme = "README.md"
classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]
dependencies = [
  "vtk>=9.0.1"
]

[project.optional-dependencies]
testing = ["assess", "pandas"]
optimisation = ["pyroltrilinos"]

[tool.setuptools]
packages = ["gadopt"]
