# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  lib:
    taskfile: ../../../.tasks.lib.yml
    internal: true

tasks:
  run-tests:
    vars:
      file: "base_case.py"
    sources:
      - "{{.file}}"
    generates:
      - "params.log"
      - "*.pvd"
      - "*.vtu"
      - "*.pvtu"
      - "*.h5"
      - "*.gif"
      - "output/"
    cmds:
      - task: lib:run-python
        vars: { file: "{{.file}}" }
