# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  lib:
    taskfile: ../../.tasks.lib.yml
    internal: true

tasks:
  run-tests:
    vars:
      file: "smoothing.py"
    sources:
      - "{{.file}}"
    generates:
      - "params.log"
      - "*.pvd"
      - "*.vtu"
      - "*.pvtu"
      - "*.h5"
      - "output/"
      - "original_temperature/"
    cmds:
      - ln -s "../../tests/adjoint_2d_cylindrical/Checkpoint230.h5" smoothing-example.h5
      - defer: rm smoothing-example.h5
      - task: lib:run-python
        vars: { file: "{{.file}}" }

  convert-notebooks:
    cmds:
      - ln -s "../../tests/adjoint_2d_cylindrical/Checkpoint230.h5" smoothing-example.h5
      - defer: rm smoothing-example.h5
      - task: lib:convert-notebook
        vars:
          file_base: "smoothing"

  add-files-to-archive:
    cmds:
      - task: lib:add-files-to-archive
        vars:
          archive: "{{.archive}}"
          files: ["smoothing.ipynb"]
