graph TD
  base[Base]

  subgraph model_diagnostics[Model Diagnostics]
  dynamic_topography[Dynamic Topography]
  end

  subgraph adjoint[Adjoint]
  adjoint_forward[Forward] --> inverse[Inverse]
  end

  subgraph geometry[Geometry]
  cylindrical_2d[2D Cylindrical] --> spherical_3d[3D Spherical]
  end

  subgraph gplates[GPlates]
  gplates_global["Global GPlates"]
  end

  subgraph dimension[Dimension]
  cartesian_3d[3D Cartesian]
  end

  subgraph bcs[Boundary Conditions]
  free_surface[Free Surface]
  end

  subgraph compressibility[Compressibility]
  tala[TALA] --> ala[ALA] --> visualise_ala[ALA Nullspace]
  end

  subgraph rheology[Rheology]
  viscoplastic[Viscoplastic]
  end

  base --> dimension
  base --> compressibility
  base --> rheology
  base --> geometry
  base --> bcs
  base --> adjoint
  base --> model_diagnostics
  geometry --> gplates

  click base "mantle_convection/base_case"
  click tala "mantle_convection/2d_compressible_TALA"
  click ala "mantle_convection/2d_compressible_ALA"
  click visualise_ala "mantle_convection/visualise_ALA_p_nullspace"
  click viscoplastic "mantle_convection/viscoplastic_case"
  click cartesian_3d "mantle_convection/3d_cartesian"
  click cylindrical_2d "mantle_convection/2d_cylindrical"
  click spherical_3d "mantle_convection/3d_spherical"
  click gplates_global "mantle_convection/gplates_global"
  click adjoint_forward "mantle_convection/adjoint_forward"
  click inverse "mantle_convection/adjoint"
  click free_surface "mantle_convection/free_surface"
  click dynamic_topography "mantle_convection/dynamic_topography"
