# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  base_case: ./base_case
  2d_compressible_ALA: ./2d_compressible_ALA
  2d_compressible_TALA: ./2d_compressible_TALA
  viscoplastic_case: ./viscoplastic_case
  2d_cylindrical: ./2d_cylindrical
  3d_spherical: ./3d_spherical
  3d_cartesian: ./3d_cartesian
  adjoint: ./adjoint
  gplates_global: ./gplates_global
  free_surface: ./free_surface
  dynamic_topography: ./dynamic_topography
  Drucker_Prager: ./Drucker_Prager

tasks:
  run-tests:
    deps:
      - "base_case:run-tests"
      - "2d_compressible_ALA:run-tests"
      - "2d_compressible_TALA:run-tests"
      - "viscoplastic_case:run-tests"
      - "2d_cylindrical:run-tests"
      - "3d_spherical:run-tests"
      - "3d_cartesian:run-tests"
      - "adjoint:run-tests"
      - "gplates_global:run-tests"
      - "free_surface:run-tests"
      - "dynamic_topography:run-tests"
      - "Drucker_Prager:run-tests"

