# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  base_case: ./base_case
  2d_compressible_ALA: ./2d_compressible_ALA
  2d_compressible_TALA: ./2d_compressible_TALA
  viscoplastic_case: ./viscoplastic_case
  2d_cylindrical: ./2d_cylindrical
  3d_spherical: ./3d_spherical
  3d_cartesian: ./3d_cartesian
  adjoint: ./adjoint
  gplates_global: ./gplates_global
  free_surface: ./free_surface
  dynamic_topography: ./dynamic_topography
  Drucker_Prager: ./Drucker_Prager

vars:
  mantle_cases:
    - "base_case"
    - "2d_compressible_ALA"
    - "2d_compressible_TALA"
    - "viscoplastic_case"
    - "2d_cylindrical"
    - "3d_spherical"
    - "3d_cartesian"
    - "adjoint"
    - "gplates_global"
    - "free_surface"
    - "dynamic_topography"
    - "Drucker_Prager"

tasks:
  run-tests:
    deps:
      - for: { var: mantle_cases }
        task: "{{.ITEM}}:run-tests"

  convert-notebooks:
    deps:
      - for: { var: mantle_cases }
        task: "{{.ITEM}}:convert-notebooks"

  add-files-to-archive:
    deps:
      - for: { var: mantle_cases }
        task: "{{.ITEM}}:add-files-to-archive"
        vars:
          archive: "{{.archive}}"
