# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  lib:
    taskfile: ../../../.tasks.lib.yml
    internal: true

tasks:
  run-tests:
    run: once
    vars:
      file: "base_case.py"
    sources:
      - "{{.file}}"
    generates:
      - "params.log"
      - "*.pvd"
      - "*.vtu"
      - "*.pvtu"
      - "*.h5"
      - "output/"
    cmds:
      - task: lib:run-python
        vars: { file: "{{.file}}" }

  convert-notebooks:
    cmds:
      - task: lib:convert-notebook
        vars:
          file_base: "base_case"

  add-files-to-archive:
    cmds:
      - task: lib:add-files-to-archive
        vars:
          archive: "{{.archive}}"
          files: ["base_case.ipynb"]
