# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  2d_cylindrical: ./2d_cylindrical
  free_surface: ./free_surface
  compositional_buoyancy: ./compositional_buoyancy
  thermochemical_buoyancy: ./thermochemical_buoyancy

vars:
  mm_cases:
    - "2d_cylindrical"
    - "free_surface"
    - "compositional_buoyancy"
    - "thermochemical_buoyancy"

tasks:
  run-tests:
    deps:
      - for: { var: mm_cases }
        task: "{{.ITEM}}:run-tests"

  convert-notebooks:
    deps:
      - for: { var: mm_cases }
        task: "{{.ITEM}}:convert-notebooks"

  add-files-to-archive:
    deps:
      - for: { var: mm_cases }
        task: "{{.ITEM}}:add-files-to-archive"
        vars:
          archive: "{{.archive}}"
