graph TD
  base[Base]
  cylindrical_2d[2D Cylindrical]

  base --> cylindrical_2d

  click base "glacial_isostatic_adjustment/base_case"
  click cylindrical_2d "glacial_isostatic_adjustment/2d_cylindrical"
