# 3d box model based on weerdesteijn et al 2023

from gadopt import *
from weerdesteijn_2d import Weerdesteijn2d
import argparse
parser = argparse.ArgumentParser()
parser.add_argument("--dx", default=5, type=float, help="Horizontal resolution in km", required=False)
parser.add_argument("--refined_surface", action='store_false', help="Use refined surface mesh")
parser.add_argument("--nz", default=80, type=int, help="Number of vertical layers", required=False)
parser.add_argument("--dt", default=50, type=float, help="Timestep in years", required=False)
parser.add_argument("--Tend", default=110e3, type=float, help="Simulation end time in years", required=False)
args = parser.parse_args()

class Weerdesteijn3d(Weerdesteijn2d):
    name = "weerdesteijn-3d"
    vertical_component = 2

    def __init__(self, refined_surface=True, **kwargs):
        self.refined_surface = refined_surface
        log("refined pre init",refined_surface)
        super().__init__(**kwargs)

    def setup_surface_mesh(self):
        # Surface mesh with refinement near ice load can be generated by running:
        # gmsh -2 weerdesteijn_box_refined_surface.geo -setnumber refined_dx 5
        # which gives resolution of 5 km near ice load. 
        log("refined", self.refined_surface)
        if self.refined_surface:
            return Mesh(f"./weerdesteijn_box_refined_surface_{round(self.dx/1000)}km.msh", name="surface_mesh")
        else:
            return SquareMesh(self.nx, self.nx, self.L)


    def initialise_r(self):
        return pow(pow(self.X[0], 2) + pow(self.X[1], 2), 0.5)

    def setup_bcs(self):
        super().setup_bcs()
        self.stokes_bcs[self.bottom_id] = {'uz': 0}
        self.stokes_bcs[3] = {'uy': 0}
        self.stokes_bcs[4] = {'uy': 0}
    
    def checkpoint_filename(self):
        return f"/g/data/vo05/ws9229/viscoelastic/3d_weerdesteijn/{self.name}-refinedsurface{self.refined_surface}-dx{round(self.dx/1000)}km-nz{self.nz}-dt{self.dt_years}years-chk.h5"
    
    def displacement_filename(self):
        return f"displacement-{self.name}-refinedsurface{self.refined_surface}-dx{round(self.dx/1000)}km-nz{self.nz}-dt{self.dt_years}years.dat"


if __name__ == "__main__":
    log("refined pre init",args.refined_surface)
    simulation = Weerdesteijn3d(dx=args.dx*1e3, refined_surface=args.refined_surface, nz=args.nz, dt_years=args.dt, Tend_years=args.Tend)
    simulation.run_simulation()
