# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

includes:
  lib:
    taskfile: ../../../.tasks.lib.yml
    internal: true

  base_case: ../base_case

tasks:
  prereq-global:
    deps: [":base_case:run-tests"]
    if: "{{ne .ROOT_TASKFILE .TASKFILE}}"
  prereq-local:
    deps: ["base_case:run-tests"]
    if: "{{eq .ROOT_TASKFILE .TASKFILE}}"

  run-tests:
    vars:
      file: "dynamic_topography.py"
    deps:
      - prereq-global
      - prereq-local
    sources:
      - "{{.file}}"
      - "../base_case/Final_State.h5"
    generates:
      - "params.log"
      - "*.pvd"
      - "*.vtu"
      - "*.pvtu"
      - "*.h5"
      - "output/"
    cmds:
      - task: lib:run-python
        vars: { file: "{{.file}}" }

  prereq-notebook-global:
    deps: [":base_case:convert-notebooks"]
    if: "{{ne .ROOT_TASKFILE .TASKFILE}}"
  prereq-notebook-local:
    deps: ["base_case:convert-notebooks"]
    if: "{{eq .ROOT_TASKFILE .TASKFILE}}"

  convert-notebooks:
    deps:
      - prereq-notebook-global
      - prereq-notebook-local
    cmds:
      - task: lib:convert-notebook
        vars:
          file_base: "dynamic_topography"

  add-files-to-archive:
    cmds:
      - task: lib:add-files-to-archive
        vars:
          archive: "{{.archive}}"
          files: ["dynamic_topography.ipynb"]
