name: Run regression tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Benchmark regression test
    runs-on: self-hosted
    container:
      image: firedrakeproject/firedrake:latest
      options: --shm-size 2g

    env:
      OMP_NUM_THREADS: 1

    steps:
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y task-spooler
          tsp -S 48
      - uses: actions/checkout@v3
      - name: Install Python dependencies
        run: |
          . /home/firedrake/firedrake/bin/activate
          python3 -m pip install -r requirements.txt
          python3 -m pip install .
      - name: Run test
        run: |
          . /home/firedrake/firedrake/bin/activate
          make -j test > test_output.log
          python -m pytest
        env:
          GADOPT_LOGLEVEL: INFO

      - name: Upload failed run log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: run-log
          path: test_output.log
