name: Run regression tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Benchmark regression test
    runs-on: self-hosted
    container:
      image: firedrakeproject/firedrake:latest

    env:
      OMP_NUM_THREADS: 1

    steps:
      - uses: actions/checkout@v3
      - name: Run test
        run: |
          . /home/firedrake/firedrake/bin/activate
          python3 -m pip install -r requirements.txt
          python3 -m pip install .
          make -j6 test > test_output.log 2>&1
          python -m pytest
        env:
          GADOPT_LOGLEVEL: INFO

      - name: Upload failed run log
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: run-log
          path: test_output.log
