name: Run regression tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  check_commit:
    runs-on: ubuntu-latest
    outputs:
      skip: ${{ steps.check_commit.outputs.skip }}
    steps:
      - name: Always run tests on workflow dispatch
        id: early_exit
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run:
          echo skip=true >> "$GITHUB_OUTPUT"
      - uses: actions/checkout@v4
        if: ${{ steps.early_exit.outputs.skip != 'true' }}
        with:
          ref: ${{ github.event.push.after || github.event.pull_request.head.sha || github.event.workflow_dispatch.ref }}
      - name: Check if message contains skip keyword
        id: check_commit
        if: ${{ steps.early_exit.outputs.skip != 'true' }}
        run: |
          message=$(git log -1 --pretty=format:'%B')
          regex="\[skip tests\]"
          if [[ "$message" =~ $regex ]]; then
            echo skip=true >> "$GITHUB_OUTPUT"
          fi
  build:
    name: Benchmark regression test
    runs-on: self-hosted
    container:
      image: firedrakeproject/firedrake:latest
      options: --shm-size 2g

    concurrency:
      group: testing-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    needs: check_commit
    if: ${{ needs.check_commit.outputs.skip != 'true' }}

    env:
      OMP_NUM_THREADS: 1

    steps:
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y task-spooler time
          tsp -S 48
      - uses: actions/checkout@v4

      - name: Load pyrol wheel from cache
        uses: actions/cache/restore@v3
        id: cache-pyrol
        with:
          path: /tmp/wheels
          key: pyrol

      - name: Build pyrol wheel
        if: steps.cache-pyrol.outputs.cache-hit != 'true'
        run: |
          curl -OL https://github.com/Kitware/CMake/releases/download/v3.28.1/cmake-3.28.1-linux-x86_64.tar.gz
          sudo tar --strip-components=1 -C /usr/local -xf cmake-3.28.1-linux-x86_64.tar.gz
          /home/firedrake/firedrake/bin/pip wheel -r requirements-git.txt -w /tmp/wheels

      - name: Save pyrol to cache
        if: steps.cache-pyrol.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: /tmp/wheels
          key: pyrol

      - name: Install Python dependencies
        run: |
          . /home/firedrake/firedrake/bin/activate
          python3 -m pip install --no-index -f /tmp/wheels pyroltrilinos
          python3 -m pip install -r requirements.txt
          python3 -m pip install .

      - name: Run test
        id: run_tests
        run: |
          . /home/firedrake/firedrake/bin/activate
          make -j test
        env:
          GADOPT_LOGLEVEL: INFO
          TS_MAXFINISHED: 100

      - name: Pytest
        id: run_pytest
        run: |
          . /home/firedrake/firedrake/bin/activate
          python -m pytest -m 'not longtest' --junit-xml=test_results.xml

      - name: Pytest report
        uses: mikepenz/action-junit-report@v4
        if: ${{ !cancelled() && steps.run_pytest.conclusion != 'skipped' }}
        with:
          check_name: Test suite report
          report_paths: test_results.xml
          include_passed: true
          annotate_only: true

      - name: Output timing information
        if: ${{ !cancelled() }}
        shell: bash
        run: |
          declare -A timings
          declare -A success

          # extract info
          for id in $(tsp | awk 'NR>1 { print $1 }'); do
            st="$(tsp -i $id)"
            command=$(sed -En 's/^Command.*python3? //p' <<< "$st")
            timings["$command"]=$(sed -n 's/^Time run: //p' <<< "$st")

            if grep -q "exit code 0" <<< "$st"; then
              success["$command"]=Yes
            else
              success["$command"]=No
              echo "$command failed:"
              tsp -c $id | tail -n 10 || true
              echo $command >> test_output.log
              tsp -c $id >> test_output.log || true
            fi
          done

          # sort by case name
          declare -a cases
          while IFS= read -r -d '' entry; do
            cases+=("$entry")
          done < <(printf "%s\0" "${!timings[@]}" | sort -z)

          printf "## Case timings\nCase | Time | Success?\n---- | ---- | ----\n" >> "$GITHUB_STEP_SUMMARY"
          for case in "${cases[@]}"; do
            printf "%s | %s | %s\n" "$case" ${timings["$case"]} ${success["$case"]} >> "$GITHUB_STEP_SUMMARY"
          done

      - name: Upload failed run log
        if: steps.run_tests.conclusion == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: run-log
          path: test_output.log
